name: Check cpp code

on: [push]

jobs:
  lint:
    runs-on:   ubuntu-latest
    container: yaishenka/docker-codestyle-checker:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint code
      run: |
        ./check.sh
